### ISSUE TITLE
Add option to change "Existing custom fields" order

### ISSUE THREAD

**Issue by kalle-1989** [SiimKirjanen/seatreg#124]
Once custom fields are created, the order cannot be changed in the SeatReg settings. Currently, the only option is to change settings JSON in the database.

There are several reasons why this feature would be helpfull: 
* It is not possible to edit existing custom fields. Therefore, the only option is to delete and create it again to change the name or to add additional values to a select option. But then the order is not as before.
* If you add new fields at a later point, they are always at the end. But this might not be the right position for your use case.

I already did some prototyping to enable this feature on my site, see https://github.com/SiimKirjanen/seatreg/compare/master...kalle-1989:seatreg:master-1.3.6-mod-admin_move_cust_field 

Initially created custom field:
![2023-05-18 15_36_55-SeatReg Settings ‹ bvltest — WordPress – Mozilla Firefox](https://github.com/SiimKirjanen/seatreg/assets/46853637/5e512a66-f989-4ea1-aab2-acb5af6605f9)
Changed custom field positions:
![2023-05-18 15_37_29-SeatReg Settings ‹ bvltest — WordPress – Mozilla  #Firefox](https://github.com/SiimKirjanen/seatreg/assets/46853637/ceff76e6-353e-48b7-a6a0-9fa095cf76d8)

I am not a CSS expert. So there is definitely room for improvement for the style. @SiimKirjanen maybe they can think about integrating this into your plugin?

**Comment by SiimKirjanen** [comment]
Hey. Can you create a pull request from your changes? I tested and works fine. Will merge your changes.

**Comment by SiimKirjanen** [comment]
Oh I was able to do it myself.

**Comment by kalle-1989** [comment]
Hey @SiimKirjanen, sorry it is not 100% clear to me what I have to do? I saw you created the pull request #125 https://github.com/SiimKirjanen/seatreg/pull/125
Is there something wrong with my CSS changes?

**Comment by SiimKirjanen** [comment]
I think you added your CSS changes to wrong place. You should add them somewhere close to https://github.com/SiimKirjanen/seatreg/blob/master/css/scss/admin/seatreg_admin.scss#L698 . So after that you should run `npm run admin-styles`
Then admin styles will be combined to css/seatreg_admin.min.css file.

**Comment by kalle-1989** [comment]
Thanks for the explanation. Sorry for the mistakes. For me WordPress plugin development, js, php and Git is something I am just learning. 
I have created a new pull request https://github.com/SiimKirjanen/seatreg/pull/126

**Comment by SiimKirjanen** [comment]
Merged the changes. Also tweaked the styles a little to make it look better.
