### ISSUE TITLE
Preset color picker with current seat color

### ISSUE THREAD

**Issue by kalle-1989** [SiimKirjanen/seatreg#129]
If you want to change the seat color, the current seat color is not adopted in the color picker. The "blue" (#0072CE) default color is always pre-set.
![2023-05-28 14_58_58-SeatReg Home ‹ bvltest — WordPress – Mozilla Firefox](https://github.com/SiimKirjanen/seatreg/assets/46853637/92f1175c-9a9f-4a15-b319-2e8f2da21f9f)

It would be nice if the current seat color is pre-set in the color picker. I already did some prototyping to enable this feature on my site, see https://github.com/SiimKirjanen/seatreg/compare/master...kalle-1989:seatreg:master-1.3.7-mod-color_picker_preset_current_color

![2023-05-28 15_00_21-SeatReg Home ‹ bvdltest — WordPress – Mozilla Firefox](https://github.com/SiimKirjanen/seatreg/assets/46853637/1951a458-abaa-4fa2-9695-16078641abcc)

If multiple boxes are selected the color of the first box is taken.
![2023-05-28 15_00_36-SeatReg Home ‹ bvdltest — WordPress – Mozilla Firefox](https://github.com/SiimKirjanen/seatreg/assets/46853637/14ab7e18-f5cc-4915-aa79-0bc5efc04289)

 @SiimKirjanen maybe you can think about integrating this feature into your plugin?

**Comment by SiimKirjanen** [comment]
@kalle-1989 looking good 👍 Can you create a pull request also?

**Comment by kalle-1989** [comment]
Sure. Thanks. 
I have created the pull request: https://github.com/SiimKirjanen/seatreg/pull/130
Please let me know if I have forgotten any dependent actions.

**Comment by SiimKirjanen** [comment]
Merged to master. Tomorrow will publish a new version of the plugin.
