### ISSUE TITLE
How do I make this accessible to customers?

### ISSUE THREAD

**Issue by Midland-Community-Farmers-Market** [SiimKirjanen/seatreg#164]
Sorry, and please bear with me, I'm extremely limited in my understanding of website design.

I run a small farmers market to raise funds for local charities.  The reservation system we had been using crashed two weeks ago, and we've been unable to revive it.  I stumbled onto the Seatreg plugin and it seems like it would be ideal.  I have created several "rooms" (which are actually our market fields; the "seats" are 10-foot spaces), but I don't understand how to make it accessible to the visitors to my website.  

My understanding is that with Seatreg, they should be able to select their desired space/seat directly from the map, make an online payment to book it (I've unchecked "Use Pending") and then have that particular "seat" blocked from subsequent customers so there will be no double-bookings. 

I'd be very grateful for some assistance in bringing this the rest of the way to fruition.

Thanks, Larry Cline (larrywcline@yahoo.com)

**Comment by SiimKirjanen** [comment]
Hello Larry
There are two ways how to make your "seat" map available to public.
1. You can add the registration address to somewhere in your website so people can click on it. That will open registration view page where people can book a seat. You can get the address when you go to plugin Home page. There under your registration you will see  "registration" item. Clicking it will open new browser tab. Copy past that address and share somewhere in your website.
2. There is also a shortcode you can use. Idea of shortcode is to add registration view directly to your website page. If you go to plugin home page then you will see "More" item below your registration.  Clicking it will open a new selection. Choosing "Shortcode" will show you your shortcode. You need to copy it. Then you need to edit your website page (in WordPress Pages menu) where you want to display the registration view. Then add the shortcode. 

![shortcode](https://github.com/SiimKirjanen/seatreg/assets/21058594/d2c10e6d-e293-44c1-b031-9265c6faf530)

Keep in mind that not all WordPress Themes play nicely with the shortcode.

**Comment by Midland-Community-Farmers-Market** [comment]
Thank you very much for your response (most of which I think I even understood!)  I'll have to gte with my web people to try to figure out where to add the shortcode, but that should not be a problem.
Am I correct in thinking there is a way to make the "Seat Selection Button" take the customer to a checkout page where they will be required to pay?  For now, mine seems to let a booking be made without any payment.  The price ($11) is mentioned when they select a space, but after they fill in the name and email address, it just says a confirmation has been sent.
Entering the registration page again, the pending bookings (which I won't be using) and approved bookings still read "0", there is no change to the spaces shown on the map as available, and the system lets the same space be booked again (which would be fairly disastrous for us!)
Once I get that fixed, I'll also need to know how to reset everything for the next week's market, so that everything is again available when I open the system again (we typically open reservations for Saturday's market at 6:00 on the preceding Monday night, and they are sold out by 6:05.)
I am unclear on the "Legends" function: is that "live" so that it reflects the status of an individual seat / space (visually indicating to customers that a space is already taken) or just something to give general information ahead of time (which spaces have electricity, in my case)?
Thanks again for your assistance.
Regards, Larry Cline


    On Friday, August 25, 2023 at 03:33:02 PM EDT, Siim Kirjanen ***@***.***> wrote:  
 
 


Hello Larry
There are two ways how to make your "seat" map available to public.
   
   - You can add the registration address to somewhere in your website so people can click on it. That will open registration view page where people can book a seat. You can get the address when you go to plugin Home page. There under your registration you will see "registration" item. Clicking it will open new browser tab. Copy past that address and share somewhere in your website.
   - There is also a shortcode you can use. Idea of shortcode is to add registration view directly to your website page. If you go to plugin home page then you will see "More" item below your registration. Clicking it will open a new selection. Choosing "Shortcode" will show you your shortcode. You need to copy it. Then you need to edit your website page (in WordPress Pages menu) where you want to display the registration view. Then add the shortcode.



Keep in mind that not all WordPress Themes play nicely with the shortcode.

**Comment by SiimKirjanen** [comment]
The "Seat Selection Button" can and can not take customer to a page directly where they can pay (all depends on configuration). But the idea is that after the booking the client will get the link to a booking status page where they can pay for the booking (they can get it via email or directly on registration page). The page looks like this 

![pay-page](https://github.com/SiimKirjanen/seatreg/assets/21058594/496db0ec-134c-456d-9382-b83580b77ddd)

After the payment is completed the booking will be market as Approved. There are many options to control this flow. I suggest you to play around with the options and see what will work best for you. 

With booking manager you can remove all existing pending and approved bookings for the next week.
The legends functionality can be used to add special meaning to specific seats (for example VIP seats or seats with electricity).
