### ISSUE TITLE
Error in translation Domain

### ISSUE THREAD

**Issue by maximaexchen** [SiimKirjanen/seatreg#177]
https://github.com/SiimKirjanen/seatreg/blob/0838fbf7d2b376a02c27137bf847320061c09972/php/SeatregConfirmBooking.php#L29

Must be:
`$this->reply = esc_html_e('This booking is already confirmed/expired/deleted', 'seatreg');
			`

**Comment by SiimKirjanen** [comment]
Hello
Can you please explain why you think `esc_html_e ` is correct?

**Comment by SiimKirjanen** [comment]
Fixed the wrong translation domains. Thank you for notifying.

**Comment by maximaexchen** [comment]
> Hello Can you please explain why you think `esc_html_e ` is correct?

Sorry I just meant the translation domain.
