### ISSUE TITLE
Problem with email validation on formfield autofill

### ISSUE THREAD

**Issue by maximaexchen** [SiimKirjanen/seatreg#178]
I got an validation error when I press tab to autocomplete on email input

https://github.com/SiimKirjanen/seatreg/blob/49189b520e2ff1a11b20b57edc7fc003d8db0348/registration/js/registration.js#L1523

I added **change** get it work:

`
$('#checkout-input-area').on('keyup change','.field-input', function(e) {
	validateInput($(this));
});
`

**Comment by SiimKirjanen** [comment]
Thank you. I pushed the change to master.
