### ISSUE TITLE
Only show entries which are bookable on seat-id-modal

### ISSUE THREAD

**Issue by maximaexchen** [SiimKirjanen/seatreg#181]
Hi.
Is there a quick way to get only bookable $roomsData in the modal (backend booking).
The problem is, if you have 3 rooms with over 100 seats, the list becomes very long.

Just a quick hint if it is possible?
As I can sea the $roomsData do not have any information about the booking status of a specific seat.
So it would be maybe possible to filter the data array for the modal.

Regards Marcus 

By the way. Fantastic job!

As soon as I am done with my current project I share my german translation files!

**Comment by SiimKirjanen** [comment]
Hey.
Yes the `$roomsData` does not have any booking status info. If you want to show only seats that are open then you need to filter the `$roomsData` here: https://github.com/SiimKirjanen/seatreg/blob/master/php/seatreg_functions.php#L1615-L1617
To get the bookings you can use https://github.com/SiimKirjanen/seatreg/blob/master/php/seatreg_functions.php#L1286-L1287 and pass them to https://github.com/SiimKirjanen/seatreg/blob/master/php/seatreg_functions.php#L1465 `seatreg_seat_id_modal ` function and too the filtering there.

**Comment by SiimKirjanen** [comment]
But keep in mind that any changes you make will be lost when plugin is updated.

**Comment by maximaexchen** [comment]
Thanks for your advice. I think I didn't get it by now... I will try to find it out. :-)

 
Yeah I know.
But my project for a small theatergroup needed asso some other additions (e.g. creatwing ticket pdfs on confirmation with custom beackground, and some other).
So I already have the update problem. :-(
If I had more time I would have done it a more generic way with some pull request. ;-)
