### ISSUE TITLE
[Stripe] Webhooks not updated when API-key is changed

### ISSUE THREAD

**Issue by bkcsoft** [SiimKirjanen/seatreg#208]
Description says it all really. If you change the api-key for stripe, the webhooks aren't updated (old one is still used). So if one is testing using their test-key, and then changes the api-key to production-key, bookings payment status will stay as "processing" instead of "completed". And if one uses auto-approval, they'll stay as pending.

Looking as [this code](https://github.com/SiimKirjanen/seatreg/blob/master/php/seatreg_functions.php#L3122-L3144) it seems like it would update if one disables and re-enables the integration. Seems like it should either inform the user that one needs to toggle it on then off, or just update it when the api-key is swapped.

**Comment by SiimKirjanen** [comment]
Hey. 
Maybe I am missing something but I think that is how it should work. Changing the Stripe API key won't change existing webhooks. The API key gives access to read/modify/delete the webhooks but I don't think they are tied together.

The main idea is to have one Stripe webhook that points to your WordPress site address. Should not matter what API key was used to create it.
I created a small PR that improves the logic a little bit.

**Comment by bkcsoft** [comment]
> Should not matter what API key was used to create it.

It does if you're either switching between prod/test in Stripe (since they effectively work like two different accounts), or if you switch to a different account.

That said, the improved logic should fix this (haven't tested it though)
