### ISSUE TITLE
Bookings are handled improperly on payment failures

### ISSUE THREAD

**Issue by bkcsoft** [SiimKirjanen/seatreg#240]
Problem description:
If a (stripe) payment fails, we get a `payment.failed`-event from Stripe. The booking is set to `status=0`. When the payment is then retried we get a `payment.success`-event, but since the booking-status is 0 (instead of 1) it isn't updated to reflect this.

Expected behaviour:
If a `payment.success`-event is received, I would expect the booking to be marked as payed, regardless of prior booking-status.

Side-note:
Also, there's no list for "discarded" (status=0) bookings in the UI.

Workaround:
My "workaround" was to update the booking in MySQL to have status=1, then resend the event in stripe.

**Comment by SiimKirjanen** [comment]
Oh, you are right. I don't know what I was thinking. I will create a fix for it.
About the "discarded" bookings. There is somewhat similar task to add deleted tab https://github.com/SiimKirjanen/seatreg/issues/161
