### ISSUE TITLE
Master registration for subscriptions [feature request]

### ISSUE THREAD

**Issue by compox95** [SiimKirjanen/seatreg#248]
Hi, I'm using the plugin (great work, thanks! I've translated it into Italian to help out) to manage bookings for an amateurs theater.

Other than buying tickets for a single show, we also have the option to buy a subscription for the whole theatrical season.
It would be great if in one of the future updates, we could set one of the room registrations as "Master" (the seasonal subscription one) and have that update all the "child" bookings (the single shows) when a booking is made on the master one.

Or be able to easily copy the bookings from one registration to others / via an xls or csv in the "Bookings">Add booking tab (instead of doing it manully for each seat ID)

**Comment by SiimKirjanen** [comment]
Hello. Thank you for the translations and the donation :+1:
I am not sure if I like the "Master" registration idea but the import bookings via file is good one. The idea is that people should be able to export existing bookings from a registration as a csv file and import it in another registration.
