### ISSUE TITLE
Open and close registration datetime support

### ISSUE THREAD

**Issue by SiimKirjanen** [SiimKirjanen/seatreg#31]
Admin can add exactly when registration starts and closes. Currently only date is supported.

**Comment by ignition3d** [comment]
Will this add the automatic opening and closing of reservations? Can you add the time as well as the date?
Thank you very much... forgive me if I didn’t have to write this question here. I can’t find how to contact you.

**Comment by SiimKirjanen** [comment]
Hey
Yes this task is about adding the time. Currently you can only set a date when registration starts and when it closes.
Just wondering what would be your use case when you want the time support?

**Comment by ignition3d** [comment]
I would like to allow the students of the school, to reserve their place in the library. every day on 2 time bands, (12h00 - 13h00 and 13h00 - 14h00), we have 30 places available every time.
Reservations, start the same morning from 9h00 to 11h00.
it would be nice to be able to schedule this throughout the year, so that the places will automatically reset every day.
I hope I was clear. I would also like to collaborate in the translation into French. thank you.

**Comment by SiimKirjanen** [comment]
hmm..okay. Currently I think that this plugin is not very well suited for your use case. Some things to think about:

- Are you planning to create two separate registrations? One for 12h00-13h00 and second for 13h00-14h00. Because with calendar mode if you book a place then this place will be booked for all day. In the next day it will be available again. Another option is to use the rooms feature. So in that case your registration have two rooms (12h00-13h00 and 13h00-14h00). So students can choose the right time. In that case you don't need two registrations.
- Can students book places in the future? For example next month?

**Comment by ignition3d** [comment]
1. Yes exactly : 
this is what I was doing, as in the image:
<img width="398" alt="Screenshot 2023-09-22 alle 15 17 02" src="https://github.com/SiimKirjanen/seatreg/assets/33983067/b6b9e4d5-15bf-45b7-afca-2bdb7ea510e4">

2. Yes. the same student can book his place every day, but he can only do it in the morning. You can’t book today for next week.
many thanks

**Comment by SiimKirjanen** [comment]
Okay in that case there are two features missing.

- Ability to set time period for each day when registration starts and when it ends
- Ability to set restrictions how far into the future person can make the booking

**Comment by SiimKirjanen** [comment]
Time restriction feature was added the main branch. Planning to publish new version of the plugin this week.
