### ISSUE TITLE
Allow automatic expiration of pending bookings

### ISSUE THREAD

**Issue by matthias-vogt** [SiimKirjanen/seatreg#34]
Hi, thanks for the nice plugin, I have a feature request.
It is currently possible to block registration completely.
By individually registering all seats so that they are in "pending" state, nobody can register any seats anymore.
A fix would be to allow the automatic expiration of pending bookings after e.g. 15 minutes as it is usually done in such systems.

**Comment by SiimKirjanen** [comment]
Hey. Good idea. I think this can be an optional feature that can be turned on and off. Currently admins can take a look at the booking manager and remove pending bookings that are old but yeah maybe that is too tedious

**Comment by SiimKirjanen** [comment]
Feature was added with version 1.15.0

**Comment by matthias-vogt** [comment]
Nice, thanks!

Am 16. Januar 2022 16:40:33 MEZ schrieb Siim Kirjanen ***@***.***>:
