### ISSUE TITLE
Remove refunded bookings from seatmap

### ISSUE THREAD

**Issue by matthias-vogt** [SiimKirjanen/seatreg#35]
After a booking is refunded (via PayPal), it is still marked as "pending" in the status page and in the seatmap. Instead, the seat should be able to be booked again by new customers.

**Comment by SiimKirjanen** [comment]
Yeah good point. Currently I have set it so when refunding happens booking is set as pending here https://github.com/SiimKirjanen/seatreg/blob/master/php/libs/SeatregPayPalIpn.php#L142-L153
Actually deleting the booking makes more sense.

**Comment by SiimKirjanen** [comment]
Change merged to master
