### ISSUE TITLE
Bookings get magically unapproved

### ISSUE THREAD

**Issue by matthias-vogt** [SiimKirjanen/seatreg#39]
Sometimes, confirmed bookings go to pending again after some time. The bookings in question were paid with paypal but I don't know if that's relevant. The `status` entry switches from `2` to `1` for these bookings.

I am using this plugin in production right now and this keeps happening but only for some bookings.
Do you have an idea why that could be?

![2022-01-07-152040_2118x912_scrot](https://user-images.githubusercontent.com/4030513/148557431-6a03dfac-754a-4088-a626-9054c87ed812.png)

**Comment by SiimKirjanen** [comment]
Can you click on the booking activity button? It should show some logs.

**Comment by matthias-vogt** [comment]
![IMG_20220108_023437](https://user-images.githubusercontent.com/4030513/148626406-b75cacb8-2e83-43a3-9331-dc65cec7d92b.jpg)
It doesnt list in any logs that the booking was unapproved for these bookings

**Comment by SiimKirjanen** [comment]
I will improve the booking activity logging.

**Comment by SiimKirjanen** [comment]
I changed booking activity logging a little. I hope it will help the investigation. Also I noticed on our first picture that Payment date in not set. Are all the bookings have this problem? Or only the ones that magically go back to pending?

**Comment by SiimKirjanen** [comment]
Also do you have access to server error logs? Maybe there is some clue.

**Comment by matthias-vogt** [comment]
The missing payment date is a separate problem I think, some of the magically switching bookings have no payment date and some do. I enabled error logs and will see if I get any in the future. Thank you for improving the logging.

**Comment by SiimKirjanen** [comment]
Hey. I was able to reproduce the issue locally and I pushed fix to master.

**Comment by matthias-vogt** [comment]
Nice I will see if it happens again

**Comment by SiimKirjanen** [comment]
Hey. Did it happen again?

**Comment by matthias-vogt** [comment]
No we good, thx!
