### ISSUE TITLE
[bug]duplicating room mess up sets ID

### ISSUE THREAD

**Issue by compox95** [SiimKirjanen/seatreg#57]
Hello! First of all, many, many thanks @SiimKirjanen ! I'll use the plugin for the org I'm helping and already proceeded to translate it in Italian so that their elderly users can use it (and hopefully they'll approve my request to become a translation editor of the plugin soon, so that I can approve the translations I did).

I noticed that after you create a room, if one of the seat ID is higher than the others, regardless of the seat number forced via the map editor, it will mess up its numeration when tried to clone the room.
It will mess up the number on both the newly cloned room as well as the original!
I've been experiencing this bug since 1.22

![image](https://user-images.githubusercontent.com/5340691/187088149-754d6684-c4af-475a-9d58-273b64dc671e.png)
![image](https://user-images.githubusercontent.com/5340691/187088158-efb9433d-dc8d-4fe9-97ab-4ba18047956b.png)

Also, in the latest two versions I'm not able to select the map editor tools, but reverting back to 1.22 worked
</div>

**Comment by SiimKirjanen** [comment]
Hey. I am glad you find my plugin useful and thank you for helping with the translations 💪 

About the seat ID issue. Do you think you can provide me with step by step guide how to reproduce the issue? It would help because currently I don't see/understand the issue.

**Comment by compox95** [comment]
Glad to do it! 

Create a room, put some seats, one after another. Then move one of the last placed seats at the beginning of the row with all the seats, and re-number the seats.
Then, copy the room. Both rooms should now have the seat numbers reseted (the first seat of the row, which has an higher ID, will have the last available number)

**Comment by SiimKirjanen** [comment]
Okay thank you. I was able to reproduce the issue.

**Comment by SiimKirjanen** [comment]
Hey. I updated the plugin to version 1.25.1. It should fix the reordering issue.

**Comment by SiimKirjanen** [comment]
Lets now try to figure out why map eidtor tool is not working for you after version 1.22. Do you have any errors in your browser console log?

**Comment by compox95** [comment]
Thanks Siim! Also, with 1.25.1, the map editor works, go figure.

PS: I also finished (& approved) the italian translation for the Stable release 🎉 (if I recall correctly, that's enough for making it usable. Hope you can add it soon as we'll be opening the bookings in our small local theater in september)

**Comment by SiimKirjanen** [comment]
The translations will be taken straight from Wordpress. There is nothing for me to add. Sometimes you need to go to WordPress admin panel and there select Dashboard -> updates. There should be button to update translation files. After that you should have the new translations ready.
