### ISSUE TITLE
blank page in new theme

### ISSUE THREAD

**Issue by frbnet** [SiimKirjanen/seatreg#7]
i have change theme to Mesmerize, and now i am getting blank seat page in frontpage all works i admin mode.

**Comment by SiimKirjanen** [comment]
Hey. I tried to reproduce but was not able. Maybe I misunderstood something. Can you post some pictures and what version of WP are you using? So I can try to reproduce and fix.

**Comment by frbnet** [comment]
I found error, have install a css/js optimazer that blocked your codes some how, uninstalled it and i am back in the game.

have you considered adding shortcode feature, so you can add the registration into a page, and not going on solo page  ???

**Comment by SiimKirjanen** [comment]
Yes I have thought about it. Its in my improvements list of things to do.

**Comment by SiimKirjanen** [comment]
I added shortcode to the plugin. If you update the plugin to 1.1.0 then you can use [seatreg] or if you have more then one registration then you can provide the code. Example 👉  [seatreg code=d0ca254995]

**Comment by frbnet** [comment]
super, if you change the system to multi language i will make a danish/sweden/norway translation for you

**Comment by SiimKirjanen** [comment]
Cool. This is also in my improvements list. I will close the current issue. If you spot anything or have more improvement ideas let me know.

**Comment by frbnet** [comment]
I just finish translate all to danish  on https://translate.wordpress.org/locale/da/default/wp-plugins/seatreg/  hope you will use it 

Best regards
