### ISSUE TITLE
Problem on updating schema .

### ISSUE THREAD

**Issue by pierre-beep** [SiimKirjanen/seatreg#87]
I got an error room hight missing while trying to update the room with seats .
* {_response: {type: "error", text: "room height missing or invalid", data: null, extraData: null}}
    * _response :  {type: "error", text: "room height missing or invalid", data: null, extraData: null}
        * data :  null extraData :  null text :  "room height missing or invalid" type :  "error" }
        
        Have no idea where it comes from 

{wp-auth-check: true, server_time: 1675625499}
server_time
: 
1675625499
wp-auth-check
: 
true

**Comment by pierre-beep** [comment]
if( !property_exists($roomData->room, 'width') || !is_int($roomData->room->width) ) {
                $validationStatus->setInvalid('room width missing or invalid');
                return $validationStatus;
            }

            if( !property_exists($roomData->room, 'height') || !is_int($roomData->room->height) ) {
                $validationStatus->setInvalid('room height missing or invalid');
                return $validationStatus;
            }
the  problem shows up at tha line 224 while not using a grid from the builder

**Comment by SiimKirjanen** [comment]
Hey. Thank you for notifying about the issue. I was able to reproduce. Will try to fix asap

**Comment by pierre-beep** [comment]
Hello ,i know where it comes from . The building grid because I put 0 on a y And x axe si it doesn't find the room height . Am I right ?I would like to participate in the translation because I will translate the plugin with loco so I can send you polish and later French translation if you wish . PierreEnvoyé de mon iPhoneLe 6 févr. 2023 à 09:28, Siim Kirjanen ***@***.***> a écrit :﻿
Hey. Thank you for notifying about the issue. I was able to reproduce. Will try to fix asap

**Comment by SiimKirjanen** [comment]
I released version 1.29.4 of the plugin. It should fix the issue

**Comment by SiimKirjanen** [comment]
And yes you can send me the translations or you can upload them to https://translate.wordpress.org/projects/wp-plugins/seatreg/

**Comment by pierre-beep** [comment]
How did you fix it ? Am I able to check those releases via git?Pierre RODZOCH Envoyé de mon iPhoneLe 6 févr. 2023 à 10:00, Siim Kirjanen ***@***.***> a écrit :﻿
And yes you can send me the translations or you can upload them to https://translate.wordpress.org/projects/wp-plugins/seatreg/

**Comment by SiimKirjanen** [comment]
The fix is here: https://github.com/SiimKirjanen/seatreg/commit/e76b9c77be49217dac4c4e99918233d212388ca9
The problem was that in server side there was check to make sure room width and height were INT numbers. But actually they can also have decimal value.

**Comment by SiimKirjanen** [comment]
You can check releases here: https://github.com/SiimKirjanen/seatreg/tags

**Comment by pierre-beep** [comment]
Cool 👍 Thanks P. Envoyé de mon iPhoneLe 6 févr. 2023 à 10:23, Siim Kirjanen ***@***.***> a écrit :﻿
You can check releases here: https://github.com/SiimKirjanen/seatreg/tags

**Comment by pierre-beep** [comment]
Hello I translated But I see that loco doesn't catch everything or there
is  a part you put directly into php template like add place to .  I
couldn't translate "to" because it does not exist in any string . some
photo and files as attached file[image: Capture d’écran 2023-02-07 à
22.30.50.png][image: Capture d’écran 2023-02-07 à 22.30.32.png]



I will try to send you the french version asap.


Le lun. 6 févr. 2023 à 14:00, Siim Kirjanen ***@***.***> a
écrit :
