### ISSUE TITLE
Stripe: uncaught exception when wrong API key is used

### ISSUE THREAD

**Issue by omtr** [SiimKirjanen/seatreg#97]
Hi,

just wanted to let you know: Wordpress reports a critical error when you try to use a public stripe key instad of a secret one.

The error message is:
Uncaught (Status 403) (Request req_jorHYzt03R3PPm) This API call cannot be made with a publishable API key. Please use a secret API key. You can find a list of your API keys at https://dashboard.stripe.com/account/apikeys

when you use the secret API key in the correct way, SeatReg works fine when you save the settings.

**Comment by SiimKirjanen** [comment]
Added with version 1.32.3
