### ISSUE TITLE
Feedback form prevents settings from being saved

### ISSUE THREAD

**Issue by bkcsoft** [SiimKirjanen/seatreg#99]
When pressing `Save Changes` on the settings-page I get an error in the console-log that emanate from the feedback-form.

![2023-03-22-141621_855x107_scrot](https://user-images.githubusercontent.com/4726179/226916364-06d8dd0e-dc0e-414b-af94-dc091f33d4fa.png)
![2023-03-22-141824_730x311_scrot](https://user-images.githubusercontent.com/4726179/226916570-cc81ab26-e2e1-427d-99fe-dd4c6d0d5ac0.png)

I'm running WP 6.1.1 and SeatReg 1.31.1

I've managed to figure out the schema for changing them manually in the meanwhile, but it's way easier to add custom fields in the settings page than manually writing JSON and updating them in a mysql-prompt :sweat_smile:

**Comment by SiimKirjanen** [comment]
Seems like there is a conflict. What is this feedback-form you are referring to? Is it another plugin?
I am not sure how to reproduce the issue
